config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :events do
    get :events_data, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :occurance_date, presence: true
  validates :repeat_interval, presence: true

  scope :active, -> { where(active: true) }

  def self.interval_types
    %i[singular daily weekly monthly yearly]
  end

  # retrieves occurrences for array of events
  def self.occurrences_between(events, period_from, period_to)
    result =
      events.map do |event|
        event.occurrences(period_from, period_to)
      end

    result.flatten.sort_by! { |occ| occ[:occurance_date] }
  end

  # retrieves occurrences for event instance
  # returns array of hashs which will be used for calendar render
  def occurrences(period_from, period_to)
    schedule = IceCube::Schedule.from_hash(settings)
    occurances = schedule.occurrences_between(period_from, period_to)
    occurances.map do |occ_date|
      {
        id: id,
        title: title,
        user: user,
        occurance_date: occ_date
      }
    end
  end

  def build_shedule_settings
    repeat_rule = if repeat_interval.to_sym == :singular
                    IceCube::Rule.daily.count(1)
                  else
                    IceCube::Rule.send(repeat_interval)
                  end

    schedule = IceCube::Schedule.new(occurance_date)
    schedule.add_recurrence_rule(repeat_rule)

    self[:settings] = schedule.to_hash
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy

  validates :name, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  before_save { self.email = email.downcase }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :logged_in_user
  before_action :set_locale

  include SessionsHelper

  private

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = t('messages.please_log_in')
    redirect_to login_url
  end

  def set_locale
    locale = if session[:locale]
               session[:locale]
             else
               http_accept_language.compatible_language_from(I18n.available_locales)
             end
    if locale && I18n.available_locales.include?(locale.to_sym)
      session[:locale] = I18n.locale = locale.to_sym
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    store_location
  end

  def events_data
    period_from = params[:period_from].to_date
    period_to = params[:period_to].to_date

    events = params[:all_events] ? Event.active : current_user.events.active
    @events = Event.occurrences_between(events, period_from, period_to)
  end

  def show; end

  def new
    @event = current_user.events.build
  end

  def edit; end

  def create
    @event = current_user.events.new(event_params)
    @event.build_shedule_settings

    if @event.save
      flash[:success] = t('messages.event_created')
      render :index
    else
      render :new
    end
  end

  def update
    @event.attributes = event_params
    @event.build_shedule_settings

    if @event.save
      flash[:success] = t('messages.event_updated')
      render :index
    else
      render :edit
    end
  end

  def destroy; end

  private

  def set_event
    @event = Event.find_by(id: params.fetch(:id, nil))
  end

  def event_params
    params.require(:event).permit(:title, :occurance_date, :user_id,
                                  :repeat_interval)
  end

  def correct_user
    redirect_back_or root_url unless current_user?(@event.user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in_user, only: %i[new create]
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_back_or root_url
    else
      flash.now[:danger] = t('messages.invalid_credintials')
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update]
  before_action :correct_user, only: %i[edit update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t('messages.welcome')
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = t('messages.profile_updated')
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def default_date(event)
    (event.occurance_date || DateTime.now).strftime('%Y-%m-%dT%H:%M')
  end

  def custom_edit_event_path(event)
    return edit_event_path(event[:id]) if current_user?(event[:user])

    event_path(event[:id])
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/views/events/_event.html.slim
tr
  td = link_to event[:title], edit_event_path(event)
  td = I18n.localize event[:occurance_date], format: :short

app/views/events/_form.html.slim
= simple_form_for @event do |f|
  = f.input :title
  = f.input :occurance_date, as: :datetime, html5: true,
            input_html: { value: default_date(@event) }
  = f.input :repeat_interval, collection: Event.interval_types,
            selected: @event.repeat_interval || :singular
  = f.submit

app/views/events/edit.html.slim
h1 = t('.title')
= render partial: 'form'

app/views/events/index.html.slim
.row
  .col-md-3
    - if params[:all_events]
      = link_to t('.my_events'), events_path
    - else
      = link_to t('.all_events'), events_path(all_events: true)
  .col-md-3
    = link_to t('.add_new_event'), new_event_path
.row
  .col-md-12
    #calendar

app/views/events/new.html.slim
h1 = t('.title')
= render partial: 'form'

app/views/events/show.html.slim
h2 class="card-header"
  = @event.title
.form-group
  = label @event, :occurance_date
  = text_field @event, :occurance_date,
               value: I18n.localize(@event.occurance_date, format: :short),
               class: 'form-control', disabled: true
.form-group
  = label @event, :user
  = text_field @event, :user, value: @event.user.name, class: 'form-control',
               disabled: true
.form-group
  = label @event, :repeat_interval
  = text_field @event, :repeat_interval, value: @event.repeat_interval,
               class: 'form-control', disabled: true

app/views/layouts/_header.html.slim
header class="navbar navbar-fixed-top navbar-inverse"
  .container
    = link_to t('app_title'), root_path, id: "logo"
    nav
      ul class="nav navbar-nav navbar-right"
        li
          = link_to t('home'), root_path
        - if logged_in?
          li
            = link_to t('to_users'), users_path
          li class="dropdown"
            a href="#" class="dropdown-toggle" data-toggle="dropdown"
              Account <b class="caret"></b>
            ul class="dropdown-menu"
              li
                = link_to t('profile'), current_user
              li
                = link_to t('settings'), edit_user_path(current_user)
              li class="divider"
              li
                = link_to t('log_out'), logout_path, method: :delete
        - else
          li
            = link_to t('log_in'), login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title EventsCalendar
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render partial: 'layouts/header'
    .container
      - flash.each do |message_type, message|
        div class="alert.alert-#{message_type}"
          = message
      = yield

app/views/shared/_error_message.html.slim
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      = "The form contains #{pluralize(@user.errors.count, 'error')}"
    ul
      - @user.errors.full_messages.each do |msg|
        li = msg

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  = f.input :name
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.submit

app/views/users/_user.html.slim
li
  = link_to user.name, user

app/views/users/edit.html.slim
h1 = t('users.edit.title')
.row
  .col-md-6.col-md-offset-3
    = simple_form_for @user do |f|
      = render 'form'

app/views/users/index.html.slim
h1 = t('users.index.title')
ul
  = render @users

app/views/users/new.html.slim
h1 = t('users.new.title')
.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/users/show.html.slim
.row
  .col
    = @user.name
  .col
    = @user.email